apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.hg.com
spec:
  group: samplecrd.hg.com
  versions: 
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cidr: 
                type: string
              gateway: 
                type: string
  names:
    kind: network
    plural: networks
  scope: Namespaced